language: java

jdk:
  - oraclejdk8

sudo: false

services:
  - redis-server

cache:
  directories:
  - .autoconf
  - $HOME/.m2

addons:
  apt:
    packages:
      - oracle-java8-installer

install: 
  - ./eureka/mvn clean package
  - ./zuul/mvn clean package
  - ./rest-api/mvn clean package
