language: java

jdk:
  - oraclejdk8

sudo: false

services:
  - redis-server

cache:
  directories:
  - .autoconf
  - $HOME/.m2

addons:
  apt:
    packages:
      - oracle-java8-installer

script: ./build.sh
