version: '2'
services:

  api-gateway-manager:
    image: registry.gzq.chanjet.com/hitdavid/api-gateway-manager:2017.06.15.012
    network_mode: bridge
    links:
      - eureka:eureka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8001:8001

  api-gateway:
    image: registry.gzq.chanjet.com/hitdavid/api-gateway:2017.06.15.012
    network_mode: bridge
    links:
      - eureka:eureka
      - api-gateway-manager:api-gateway-manager
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8000:8000

  eureka:
    image: registry.gzq.chanjet.com/hitdavid/eureka:2017.06.15.012
    network_mode: bridge
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - 8761:8761