spring:
  application:
    name: eureka

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.33.165:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
  instance:
    statusPageUrlPath: /info
    healthCheckUrlPath: /health
    appname: eureka
    non-secure-port: 8761
    non-secure-port-enabled: true
    ip-address: 172.16.33.165
    prefer-ip-address: true